version: '3'

services: 

  # Proxies requests to internal service
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on: 
      - authentication
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80

  user:
    image: user
    container_name: user
    build: 
      context: ./user
      target: debug
    volumes: 
      - ./user:/app
    ports: 
      - 3000:3000
    restart: on-failure

  # Authentication service
  authentication:
    image: authentication
    container_name: authentication
    build: 
      context: ./authentication
      target: debug
    ports: 
      - 3001:3000
    volumes: 
      - ./authentication:/app
    restart: always