version: '3'

services: 

  # Proxies requests to internal service
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on: 
      - authentication
      - user
      - rabbitmq
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 15671:15671
      - 5672:5672

  user:
    image: user
    container_name: user
    build: 
      context: ./user
      target: debug
    volumes: 
      - ./user:/app
    ports: 
      - 3000:3000
    restart: on-failure

  # Authentication service
  authentication:
    image: authentication
    container_name: authentication
    depends_on:
      - rabbitmq
    build: 
      context: ./authentication
      target: debug
    ports: 
      - 3001:3000
    volumes: 
      - ./authentication:/app
      - /app/node_modules
    restart: always

  # Authentication service
  microservice1:
    image: microservice1
    container_name: microservice1
    depends_on:
      - rabbitmq
    build: 
      context: ./microservice1
      target: debug
    ports: 
      - 3002:3000
    volumes: 
      - ./microservice1:/app
      - /app/node_modules
    restart: always

  # Authentication service
  microservice2:
    image: microservice2
    container_name: microservice2
    depends_on:
      - rabbitmq
    build: 
      context: ./microservice2
      target: debug
    ports: 
      - 3003:3000
    volumes: 
      - ./microservice2:/app
      - /app/node_modules
    restart: always